"""oversight schema

Revision ID: 5a7a76a52406
Revises: 
Create Date: 2026-07-25 17:51:07.227794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7a76a52406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('topic_cluster', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_region'), 'complaints', ['region'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('school_name', sa.String(length=300), nullable=True),
    sa.Column('menu_description', sa.Text(), nullable=True),
    sa.Column('portions_served', sa.Integer(), nullable=True),
    sa.Column('cost_reported', sa.Float(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('photo_verifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_reports_region'), 'daily_reports', ['region'], unique=False)
    op.create_index(op.f('ix_daily_reports_verification_status'), 'daily_reports', ['verification_status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('budget_reported', sa.Float(), nullable=True),
    sa.Column('portions_reported', sa.Integer(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_region'), 'reports', ['region'], unique=False)
    op.create_table('score_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('cost_per_portion', sa.Float(), nullable=True),
    sa.Column('cost_deviation_percent', sa.Float(), nullable=True),
    sa.Column('is_cost_plausible', sa.Boolean(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_results_id'), 'score_results', ['id'], unique=False)
    op.create_index(op.f('ix_score_results_report_id'), 'score_results', ['report_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('assigned_schools', sa.JSON(), nullable=False),
    sa.Column('daily_meal_volume', sa.Integer(), nullable=False),
    sa.Column('compliance_status', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_trend', sa.JSON(), nullable=False),
    sa.Column('watchlist_status', sa.String(), nullable=False),
    sa.Column('watchlist_reason', sa.Text(), nullable=False),
    sa.Column('last_inspection_date', sa.String(), nullable=False),
    sa.Column('repeated_issue_categories', sa.JSON(), nullable=False),
    sa.Column('coverage_notes', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('issue_category', sa.String(), nullable=False),
    sa.Column('priority_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('nutrition_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('detected_items', sa.JSON(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('menu_composition', sa.JSON(), nullable=True),
    sa.Column('meets_standard', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_results_daily_report_id'), 'nutrition_results', ['daily_report_id'], unique=False)
    op.create_index(op.f('ix_nutrition_results_id'), 'nutrition_results', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('nutrition_concern_score', sa.Integer(), nullable=False),
    sa.Column('cost_anomaly_score', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Integer(), nullable=False),
    sa.Column('final_priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_label', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('issue_category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sla', sa.String(), nullable=False),
    sa.Column('assigned_unit', sa.String(), nullable=False),
    sa.Column('escalation_level', sa.String(), nullable=False),
    sa.Column('linked_vendor_id', sa.String(), nullable=False),
    sa.Column('linked_vendor_name', sa.String(), nullable=False),
    sa.Column('linked_region', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('linked_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('audit_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('linked_entity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ocr_result', sa.Text(), nullable=True),
    sa.Column('image_text_match_score', sa.Float(), nullable=True),
    sa.Column('duplicate_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_reviews')
    op.drop_table('evidence')
    op.drop_table('tickets')
    op.drop_table('signals')
    op.drop_table('risk_assessments')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_nutrition_results_id'), table_name='nutrition_results')
    op.drop_index(op.f('ix_nutrition_results_daily_report_id'), table_name='nutrition_results')
    op.drop_table('nutrition_results')
    op.drop_table('cases')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_score_results_report_id'), table_name='score_results')
    op.drop_index(op.f('ix_score_results_id'), table_name='score_results')
    op.drop_table('score_results')
    op.drop_index(op.f('ix_reports_region'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_daily_reports_verification_status'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_region'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_region'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
